// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) 
	{
		int bigcount=0;
		int smallcount=0;
		int n=Integer.parseInt(args[0]);
		for(int i=0; i<n; i++)
		{
			double num=Math.random();
			if(num>0.5)
			{
				bigcount++;
			}
			else
			{
				smallcount++;
			}
		}
		if(smallcount>0)
		{
			double ratio=(double)smallcount/(double)bigcount;
			System.out.println("> 0.5:  "+smallcount+" times");
			System.out.println("<= 0.5: "+bigcount+" times");
			System.out.println("Ratio:  "+ratio);

		}
		else
		{
			System.out.println("> 0.5: "+smallcount+" times");
			System.out.println("<= 0.5: "+bigcount+" times");
		}


	    
	}
}
